<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Song;

class SongSeeder extends Seeder
{
    const ITEMS = [
        ["Nikes","","Christopher Breaux","27"],
        ["Ivy","","Christopher Breaux","27"],
        ["Pink + White","","Christopher Breaux","27"],
        ["Be Yourself","","Buddy Ross","27"],
        ["Solo","","Christopher Breaux","27"],
        ["Skyline To","","Christopher Breaux","27"],
        ["Self Control","","Christopher Breaux","27"],
        ["Good Guy","","Christopher Breaux","27"],
        ["Nights","","Christopher Breaux","27"],
        ["Solo (Reprise)","","André Benjamin","27"],
        ["Pretty Sweet","","Christopher Breaux","27"],
        ["Facebook Story","","Sebastian Akchoté","27"],
        ["Close to You","","Christopher Breaux","27"],
        ["White Ferrari","","Christopher Breaux","27"],
        ["Seigfried","","Christopher Breaux","27"],
        ["Godspeed","","Christopher Breaux","27"],
        ["Futura Free","","Christopher Breaux","27"],
        ["Start","","Christopher Breaux","28"],
        ["Thinkin Bout You","","Christopher Breaux","28"],
        ["Fertilizer","","James Fauntleroy","28"],
        ["Sierra Leone","","Christopher Breaux","28"],
        ["Sweet Life","","Christopher Breaux","28"],
        ["Not Just Money","","Rosie Watson","28"],
        ["Super Rich Kids","","Christopher Breaux","28"],
        ["Pilot Jones","","Christopher Breaux","28"],
        ["Crack Rock","","Christopher Breaux","28"],
        ["Pyramids","","Christopher Breaux","28"],
        ["Lost","","Christopher Breaux","28"],
        ["White","","Christopher Breaux","28"],
        ["Monks","","Christopher Breaux","28"],
        ["Bad Religion","","Christopher Breaux","28"],
        ["Pink Matter","","Christopher Breaux","28"],
        ["Forest Gump","","Christopher Breaux","28"],
        ["End","","Christopher Breaux","28"],
        ["How You Like That","","Teddy","26"],
        ["Ice Cream (feat. Selena Gomez)","","Bekuh Boom","26"],
        ["Pretty Savage","","Teddy","26"],
        ["Bet You Wanna (feat. Cardi B)","","Tommy Brown","26"],
        ["Lovesick Girls","","Teddy","26"],
        ["Crazy Over You","","Bekuh Boom","26"],
        ["Love To Hate Me","","Tushar Apte","26"],
        ["You Never Know","","Bekuh Boom","26"],
        ["Pink Venom","","Teddy Park","25"],
        ["Shut Down","","Teddy Park","25"],
        ["Typa Girl","","Bekuh Boom","25"],
        ["Yeah Yeah Yeah","","Kush","25"],
        ["Hard to Love","","Freddy Wexler","25"],
        ["The Happiest Girl","","Teddy Sinclair","25"],
        ["Tally","","Nat Dunn","25"],
        ["Ready For Love","","Teddy Park","25"],
        ["T-Shirt","","Foo Fighters","24"],
        ["Run","","Foo Fighters","24"],
        ["Make It Right","","Foo Fighters","24"],
        ["The Sky Is a Neighborhood","","Foo Fighters","24"],
        ["La Dee Da","","Foo Fighters","24"],
        ["Dirty Water","","Foo Fighters","24"],
        ["Arrows","","Foo Fighters","24"],
        ["Happy Ever After (Zero Hour)","","Foo Fighters","24"],
        ["Sunday Rain","","Foo Fighters","24"],
        ["The Line","","Foo Fighters","24"],
        ["Concrete and Gold","","Foo Fighters","24"],
        ["Making a Fire","","Foo Fighters","23"],
        ["Shame Shame","","Foo Fighters","23"],
        ["Cloudspotter","","Foo Fighters","23"],
        ["Waiting on a War","","Foo Fighters","23"],
        ["Medicine at Midnight","","Foo Fighters","23"],
        ["No Son of Mine","","Foo Fighters","23"],
        ["Holding Poison","","Foo Fighters","23"],
        ["Chasing Birds","","Foo Fighters","23"],
        ["Love Dies Young","","Foo Fighters","23"],
        ["Rescued","","Foo Fighters","22"],
        ["Under You","","Foo Fighters","22"],
        ["Hearing Voices","","Foo Fighters","22"],
        ["But Here We Are","","Foo Fighters","22"],
        ["The Glass","","Foo Fighters","22"],
        ["Nothing at All","","Foo Fighters","22"],
        ["Show Me How","","Foo Fighters","22"],
        ["Beyond Me","","Foo Fighters","22"],
        ["The Teacher","","Foo Fighters","22"],
        ["Rest","","Foo Fighters","22"],
        ["!!!!!!!","","Finneas O'Connell","21"],
        ["Bad Guy","","Finneas O'Connell","21"],
        ["Xanny","","Finneas O'Connell","21"],
        ["You Should See Me in a Crown","","Finneas O'Connell","21"],
        ["All the Good Girls Go to Hell","","Finneas O'Connell","21"],
        ["Wish You Were Gay","","Finneas O'Connell","21"],
        ["When the Party's Over","","Finneas O'Connell","21"],
        ["8","","Finneas O'Connell","21"],
        ["My Strange Addiction","","Finneas O'Connell","21"],
        ["Bury a Friend","","Finneas O'Connell","21"],
        ["Ilomilo","","Finneas O'Connell","21"],
        ["Listen Before I Go","","Finneas O'Connell","21"],
        ["I Love You","","Finneas O'Connell","21"],
        ["Goodbye","","Finneas O'Connell","21"],
        ["Getting Older","","Finneas O'Connell","20"],
        ["I Didn't Change My Number","","Finneas O'Connell","20"],
        ["Billie Bossa Nova","","Finneas O'Connell","20"],
        ["my future","","Finneas O'Connell","20"],
        ["Oxytocin","","Finneas O'Connell","20"],
        ["Goldwing","","Finneas O'Connell","20"],
        ["Lost Cause","","Finneas O'Connell","20"],
        ["Halley's Comet","","Finneas O'Connell","20"],
        ["Not My Responsibility","","Finneas O'Connell","20"],
        ["OverHeated","","Finneas O'Connell","20"],
        ["Everybody Dies","","Finneas O'Connell","20"],
        ["Your Power","","Finneas O'Connell","20"],
        ["NDA","","Finneas O'Connell","20"],
        ["Therefore I Am","","Finneas O'Connell","20"],
        ["Happier Than Ever","","Finneas O'Connell","20"],
        ["Male Fantasy","","Finneas O'Connell","20"],
        ["SKINNY","", "Finneas O'Connell", "19"],
        ["LUNCH","", "Finneas O'Connell", "19"],
        ["CHIHIRO","", "Finneas O'Connell", "19"],
        ["BIRDS OF A FEATHER","", "Finneas O'Connell", "19"],
        ["WILDFLOWER","", "Finneas O'Connell", "19"],
        ["THE GREATEST","", "Finneas O'Connell", "19"],
        ["L'AMOUR DE MA VIE","", "Finneas O'Connell", "19"],
        ["THE DINER","", "Finneas O'Connell", "19"],
        ["BITTERSUITE","", "Finneas O'Connell", "19"],
        ["BLUE","", "Finneas O'Connell", "19"],
        ["Moscow Mule","","Benito Martínez","18"],
        ["Después de la Playa","","Benito Martínez","18"],
        ["Me Porto Bonito (feat. Chencho Corleone)","","Benito Martínez","18"],
        ["Un Ratito","","Benito Martínez","18"],
        ["Party","","Benito Martínez","18"],
        ["Yo No Soy Celoso","","Benito Martínez","18"],
        ["Tarot (feat. Jhay Cortez)","","Benito Martínez","18"],
        ["Neverita","","Benito Martínez","18"],
        ["La Corriente","","Benito Martínez","18"],
        ["Efecto","","Benito Martínez","18"],
        ["Ni Bien Ni Mal","","Benito Martínez","18"],
        ["Beso","","Benito Martínez","18"],
        ["El Apagón","","Benito Martínez","18"],
        ["Ojitos Lindos (feat. Bomba Estéreo)","","Benito Martínez","18"],
        ["Andrea","","Benito Martínez","18"],
        ["Dos Mil 16","","Benito Martínez","18"],
        ["Me Fui de Vacaciones","","Benito Martínez","18"],
        ["Un Coco","","Benito Martínez","18"],
        ["Fukishima","","Benito Martínez","17"],
        ["Después de la Playa","","Benito Martínez","17"],
        ["Un Preview","","Benito Martínez","17"],
        ["Me Fui de Vacaciones","","Benito Martínez","17"],
        ["Neverita","","Benito Martínez","17"],
        ["El Apagón","","Benito Martínez","17"],
        ["La Coriente","","Benito Martínez","17"],
        ["Tarot (feat. Jhay Cortez)","","Benito Martínez","17"],
        ["Ojitos Lindos (feat. Bomba Estéreo)","","Benito Martínez","17"],
        ["Andrea","","Benito Martínez","17"],
        ["Ateo (feat. Nathy Peluso)","","Antón Álvarez Alfaro","16"],
        ["Me Maten","", "Antón Álvarez Alfaro","16"],
        ["Cambia!","", "Antón Álvarez Alfaro","16"],
        ["Nunca Estoy","", "Antón Álvarez Alfaro","16"],
        ["Comerte Entera","", "Antón Álvarez Alfaro","16"],
        ["Yate","", "Antón Álvarez Alfaro","16"],
        ["Tú Me Dejaste De Querer (feat. Niño de Elche & La Húngara)","", "Antón Álvarez Alfaro","16"],
        ["Ingobernable","", "Antón Álvarez Alfaro","16"],
        ["Oh Dios Que Video Tan Bonito","", "Antón Álvarez Alfaro","16"],
        ["Los Tontos (feat. Andrés Calamaro)","", "Antón Álvarez Alfaro","16"],
        ["El Día de Mañana","", "Antón Álvarez Alfaro","16"],
        ["Corazón Partío","", "Antón Álvarez Alfaro","16"],
        ["Demasiadas Mujeres","", "Antón Álvarez Alfaro","16"],
        ["La Sobremesa","", "Antón Álvarez Alfaro","16"],
        ["15 Step","","Thom Yorke","15"],
        ["Bodysnatchers","","Thom Yorke","15"],
        ["Nude","","Thom Yorke","15"],
        ["Weird Fishes/Arpeggi","","Thom Yorke","15"],
        ["All I Need","","Thom Yorke","15"],
        ["Faust Arp","","Thom Yorke","15"],
        ["Reckoner","","Thom Yorke","15"],
        ["House of Cards","","Thom Yorke","15"],
        ["Jigsaw Falling Into Place","","Thom Yorke","15"],
        ["Videotape","","Thom Yorke","15"],
        ["Bloom","","Thom Yorke","14"],
        ["Morning Mr Magpie","","Thom Yorke","14"],
        ["Little by Little","","Thom Yorke","14"],
        ["Feral","","Thom Yorke","14"],
        ["Lotus Flower","","Thom Yorke","14"],
        ["Codex","","Thom Yorke","14"],
        ["Give Up the Ghost","","Thom Yorke","14"],
        ["Separator","","Thom Yorke","14"],
        ["Burn the Witch","","Thom Yorke","13"],
        ["Daydreaming","","Thom Yorke","13"],
        ["Decks Dark","","Thom Yorke","13"],
        ["Desert Island Disk","","Thom Yorke","13"],
        ["Ful Stop","","Thom Yorke","13"],
        ["Glass Eyes","","Thom Yorke","13"],
        ["Identikit","","Thom Yorke","13"],
        ["The Numbers","","Thom Yorke","13"],
        ["Present Tense","","Thom Yorke","13"],
        ["Tinker Tailor Soldier Sailor Rich Man","","Thom Yorke","13"],
        ["True Love Waits","","Thom Yorke","13"],
        ["Pray You Catch Me","","Beyoncé","12"],
        ["Hold Up","","Beyoncé","12"],
        ["Don't Hurt Yourself","","Beyoncé","12"],
        ["Sorry","","Beyoncé","12"],
        ["6 Inch","","Beyoncé","12"],
        ["Daddy Lessons","","Beyoncé","12"],
        ["Love Drought","","Beyoncé","12"],
        ["Sandcastles","","Beyoncé","12"],
        ["Forward","","Beyoncé","12"],
        ["Freedom","","Beyoncé","12"],
        ["All Night","","Beyoncé","12"],
        ["Formation","","Beyoncé","12"],
        ["I'm That Girl","","Beyoncé","11"],
        ["Cozy","","Beyoncé","11"],
        ["Alien Superstar","","Beyoncé","11"],
        ["Cuff It","","Beyoncé","11"],
        ["Energy","","Beyoncé","11"],
        ["Break My Soul","","Beyoncé","11"],
        ["Church Girl","","Beyoncé","11"],
        ["Plastic Off the Sofa","","Beyoncé","11"],
        ["Virgo's Groove","","Beyoncé","11"],
        ["Move","","Beyoncé","11"],
        ["Heated","","Beyoncé","11"],
        ["Thique","","Beyoncé","11"],
        ["All Up In Your Mind","","Beyoncé","11"],
        ["Summer Renaissance","","Beyoncé","11"],
        ["Pressure","","Beyoncé","11"],
        ["Off","","Beyoncé","11"],
        ["I Been On","","Beyoncé","11"],
        ["Friends","","Beyoncé","11"],
        ["Pure/Honey","","Beyoncé","11"],
        ["Ameriican Requiem","", "Beyoncé", "10"],
        ["Blackbiird (feat. Tanner Adell, Brittney Spencer, Tiera Kennedy, Reyna Roberts)","", "Beyoncé", "10"],
        ["16 Carriages","", "Beyoncé", "10"],
        ["Protector (feat. Rumi Carter)","", "Beyoncé", "10"],
        ["My Rose","", "Beyoncé", "10"],
        ["Smoke Hour ★ Willie Nelson (feat. Willie Nelson)","", "Beyoncé", "10"],
        ["Texas Hold 'Em","", "Beyoncé", "10"],
        ["Bodyguard","", "Beyoncé", "10"],
        ["Dolly P","", "Beyoncé", "10"],
        ["Jolene","", "Beyoncé", "10"],
        ["Daughter","", "Beyoncé", "10"],
        ["Spaghettii (feat. Linda Martell & Shaboozey)","", "Beyoncé", "10"],
        ["Alligator Tears","", "Beyoncé", "10"],
        ["Smoke Hour II","", "Beyoncé", "10"],
        ["Just for Fun (feat. Willie Jones)","", "Beyoncé", "10"],
        ["II Most Wanted (feat. Miley Cyrus)","", "Beyoncé", "10"],
        ["Levii's Jeans (feat. Post Malone)","", "Beyoncé", "10"],
        ["Flamenco","", "Beyoncé", "10"],
        ["The Linda Martell Show (feat. Linda Martell)","", "Beyoncé", "10"],
        ["Ya Ya","", "Beyoncé", "10"],
        ["Oh Louisiana","", "Beyoncé", "10"],
        ["Desert Eagle","", "Beyoncé", "10"],
        ["Riiverdance","", "Beyoncé", "10"],
        ["II Hands II Heaven","", "Beyoncé", "10"],
        ["Tyrant","", "Beyoncé", "10"],
        ["Sweet ★ Honey ★ Buckiin' (feat. Shaboozey)","", "Beyoncé", "10"],
        ["Amen","", "Beyoncé", "10"],
        ["Do I Wanna Know?","","Alex Turner","9"],
        ["R U Mine?","","Alex Turner","9"],
        ["One for the Road","","Alex Turner","9"],
        ["Arabella","","Alex Turner","9"],
        ["I Want It All","","Alex Turner","9"],
        ["No. 1 Party Anthem","","Alex Turner","9"],
        ["Mad Sounds","","Alex Turner","9"],
        ["Fireside","","Alex Turner","9"],
        ["Why'd You Only Call Me When You're High?","","Alex Turner","9"],
        ["Snap Out of It","","Alex Turner","9"],
        ["Knee Socks","","Alex Turner","9"],
        ["I Wanna Be Yours","","Alex Turner","9"],
        ["Star Treatment","","Alex Turner","8"],
        ["One Point Perspective","","Alex Turner","8"],
        ["American Sports","","Alex Turner","8"],
        ["Tranquility Base Hotel & Casino","","Alex Turner","8"],
        ["Golden Trunks","","Alex Turner","8"],
        ["Four Out of Five","","Alex Turner","8"],
        ["The World's First Ever Monster Truck Front Flip","","Alex Turner","8"],
        ["Science Fiction","","Alex Turner","8"],
        ["She Looks Like Fun","","Alex Turner","8"],
        ["Batphone","","Alex Turner","8"],
        ["The Ultracheese","","Alex Turner","8"],
        ["There’d Better Be a Mirrorball","","Alex Turner","7"],
        ["I Ain’t Quite Where I Think I Am","","Alex Turner","7"],
        ["Sculptures of Anything Goes","","Alex Turner","7"],
        ["Jet Skis on the Moat","","Alex Turner","7"],
        ["Body Paint","","Alex Turner","7"],
        ["The Car","","Alex Turner","7"],
        ["Big Ideas","","Alex Turner","7"],
        ["Hello You","","Alex Turner","7"],
        ["Mr Schwartz","","Alex Turner","7"],
        ["Perfect Sense","","Alex Turner","7"],
        ["BLOOD.","","Kendrick Lamar","6"],
        ["DNA.","","Kendrick Lamar","6"],
        ["YAH.","","Kendrick Lamar","6"],
        ["ELEMENT.","","Kendrick Lamar","6"],
        ["FEEL.","","Kendrick Lamar","6"],
        ["LOYALTY. (feat. Rihanna)","","Kendrick Lamar","6"],
        ["PRIDE.","","Kendrick Lamar","6"],
        ["HUMBLE.","","Kendrick Lamar","6"],
        ["LUST.","","Kendrick Lamar","6"],
        ["LOVE. (feat. Zacari)","","Kendrick Lamar","6"],
        ["XXX. (feat. U2)","","Kendrick Lamar","6"],
        ["FEAR.","","Kendrick Lamar","6"],
        ["GOD.","","Kendrick Lamar","6"],
        ["DUCKWORTH.","","Kendrick Lamar","6"],
        ["United In Grief","","Kendrick Lamar","5"],
        ["N95","","Kendrick Lamar","5"],
        ["Worldwide Steppers","","Kendrick Lamar","5"],
        ["Die Hard (feat. Blxst & Amanda Reifer)","","Kendrick Lamar","5"],
        ["Father Time (feat. Sampha)","","Kendrick Lamar","5"],
        ["Rich Spirit","","Kendrick Lamar","5"],
        ["Jimmy Cooks (feat. 21 Savage)","","Kendrick Lamar","5"],
        ["Count Me Out","","Kendrick Lamar","5"],
        ["Blow My Load","","Kendrick Lamar","5"],
        ["Purple Hearts (feat. Summer Walker & Ghostface Killah)","","Kendrick Lamar","5"],
        ["Silent Hill (feat. Kodak Black)","","Kendrick Lamar","5"],
        ["Mother I Sober","","Kendrick Lamar","5"],
        ["Mirror","","Kendrick Lamar","5"],
        ["Crown","","Kendrick Lamar","5"],
        ["Wacced Out Murals", "", "Kendrick Lamar", "4"],
        ["Squabble Up", "", "Kendrick Lamar", "4"],
        ["Luther (feat. SZA)", "", "Kendrick Lamar", "4"],
        ["Man at the Garden", "", "Kendrick Lamar", "4"],
        ["Hey Now (feat. Dody6)", "", "Kendrick Lamar", "4"],
        ["Reincarnated", "", "Kendrick Lamar", "4"],
        ["TV Off", "", "Kendrick Lamar", "4"],
        ["Dodger Blue (feat. Siete7x & Wallie the Sensei)", "", "Kendrick Lamar", "4"],
        ["Peekaboo (feat. AzChike)", "", "Kendrick Lamar", "4"],
        ["Heart Pt. 6",  "","Kendrick Lamar", "4"],
        ["GNX (feat. Peysoh, Hitta J3 & Young Threat)", "", "Kendrick Lamar", "4"],
        ["Gloria (feat. SZA)", "", "Kendrick Lamar", "4"],
        ["Lavender Haze","","Taylor Swift","3"],
        ["Maroon","","Taylor Swift","3"],
        ["Anti-Hero","","Taylor Swift","3"],
        ["Snow on the Beach (feat. Lana Del Rey)","","Taylor Swift","3"],
        ["You're On Your Own, Kid","","Taylor Swift","3"],
        ["Midnight Rain","","Taylor Swift","3"],
        ["Question...?","","Taylor Swift","3"],
        ["Vigilante Shit","","Taylor Swift","3"],
        ["Bejeweled","","Taylor Swift","3"],
        ["Labyrinth","","Taylor Swift","3"],
        ["Karma","","Taylor Swift","3"],
        ["Sweet Nothing","","Taylor Swift","3"],
        ["Mastermind","","Taylor Swift","3"],
        ["Fortnight (feat. Post Malone)", "", "Taylor Swift", "2"],
        ["The Tortured Poets Department", "", "Taylor Swift", "2"],
        ["My Boy Only Breaks His Favourite Toys", "", "Taylor Swift", "2"],
        ["Down Bad", "", "Taylor Swift", "2"],
        ["So Long, London", "", "Taylor Swift", "2"],
        ["But Daddy I Love Him", "", "Taylor Swift", "2"],
        ["Fresh Out The Slammer", "", "Taylor Swift", "2"],
        ["Florida!!! (feat. Florence + The Machine)", "", "Taylor Swift", "2"],
        ["Guilty As Sin?", "", "Taylor Swift", "2"],
        ["Who's Afraid Of Little Old Me?", "", "Taylor Swift", "2"],
        ["I Can Fix Him (No Really I Can)", "", "Taylor Swift", "2"],
        ["LOML", "", "Taylor Swift", "2"],
        ["I Can Do It With A Broken Heart", "", "Taylor Swift", "2"],
        ["The Smallest Man Who Ever Lived", "", "Taylor Swift", "2"],
        ["The Alchemy", "", "Taylor Swift", "2"],
        ["Clara Bow", "", "Taylor Swift", "2"],
        ["The Manuscript", "", "Taylor Swift", "2"],
        ["The Fate of Ophelia", "", "Taylor Swift", "1"],
        ["Elizabeth Taylor", "", "Taylor Swift", "1"],
        ["Opalite", "", "Taylor Swift", "1"],
        ["Father Figure", "", "Taylor Swift", "1"],
        ["Eldest Daughter", "", "Taylor Swift", "1"],
        ["Ruin the Friendship", "", "Taylor Swift", "1"],
        ["Actually Romantic", "", "Taylor Swift", "1"],
        ["Wish List", "", "Taylor Swift", "1"],
        ["Wood", "", "Taylor Swift", "1"],
        ["CANCELLED!", "", "Taylor Swift", "1"],
        ["Honey", "", "Taylor Swift", "1"],
        ["The Life of a Showgirl (feat. Sabrina Carpenter)", "", "Taylor Swift", "1"]
    ];
    public function run(): void
    {
        foreach (self::ITEMS as $item) {
            $song = new Song();
	        $song->name = $item[0];
            $song->lyrics = $item[1];
            $song->songwriter = $item[2];
            $song->album_id = $item[3];
            $song->save();
        }
    }
}
